###chat
GET http://localhost:8085/api/minimax/chat?userInput=你好


###chatPrompt
GET http://localhost:8085/api/minimax/chatPrompt?userInput=你好&type=2


###返回json
GET http://localhost:8085/api/minimax/chattoJson


###拦截器
GET http://localhost:8085/api/minimax/chat_advisor?userInput="你是谁?"


###查询统计
GET http://localhost:8085/actuator/metrics/ai.prompt.tokens


###多配置
GET http://localhost:8085/api/minimax/chat_multi


###流式
GET http://localhost:8085/api/minimax/chat_stream?userInput="讲个笑话"
Accept: text/event-stream

###图片识别
GET http://localhost:8085/api/minimax/vision?question=上面写了写什么&imageUrl=https://ark-project.tos-cn-beijing.volces.com/doc_image/ark_demo_img_1.png




