# https://bailian.console.aliyun.com
spring.application.name=spring-ai-chat-minimax
server.port=8085
spring.profiles.active=minimax

# qwen model
spring.ai.openai.api-key=${MINIMAX_API_KEY}
spring.ai.openai.chat.base-url=https://api.minimaxi.com/v1
spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=MiniMax-M2.7-highspeed

# Actuator configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
